// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntdozxatyswzdtedysbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50ZG96eGF0eXN3emR0ZWR5c2JxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1OTgwMzIsImV4cCI6MjA1NzE3NDAzMn0.jWU5V--ehozGre0WxB5iXah3EC7_Z0nNe1HrnDYvVQ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);